export enum ControlKey {
  ESC = 'Escape',

  ENTER = 'Enter',

  BACKSPACE = 'Backspace',
  DELETE = 'Delete',

  ARROW_LEFT = 'ArrowLeft',
  ARROW_RIGHT = 'ArrowRight',
  ARROW_UP = 'ArrowUp',
  ARROW_DOWN = 'ArrowDown',

  TAB = 'Tab',
  CAPS_LOCK = 'CapsLock',

  SHIFT_LEFT = 'ShiftLeft',
  SHIFT_RIGHT = 'ShiftRight',

  META_LEFT = 'MetaLeft',
  META_RIGHT = 'MetaRight',

  CONTROL_LEFT = 'ControlLeft',
  CONTROL_RIGHT = 'ControlRight',

  ALT_LEFT = 'AltLeft',

  PAGE_UP = 'PageUp',
  PAGE_DOWN = 'PageDown',

  HOME = 'Home',
  END = 'End',

  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
}

export enum ShowableKey {
  SPACE = ' ',
  BACKQUOTE = '`',
  WAVY = '~',
  BANG = '!',
  AT = '@',
  POUND = '#',
  DOLLAR = '$',
  PERCET = '%',
  POWER = '^',
  AND = '&',
  STAR = '*',
  LEFT_PAREN = '(',
  RIGHT_PAREN = ')',
  SUB = '-',
  UNDERLINE = '_',
  EQ = '=',
  ADD = '+',
  LEFT_BRACK = '[',
  RIGHT_BRACK = ']',
  LEFT_BRACKET = '{',
  RIGHT_BRACKET = '}',
  BACK_SLASH = '\\',
  OR = '|',
  SEMI = ';',
  COLON = ':',
  SINGLE_QUOTE = "'",
  DOUBLE_QUOTE = '"',
  COMMA = ',',
  LT = '<',
  DOT = '.',
  GT = '>',
  SLASH = '/',
  QUESTION = '?',

  NUMBER_1 = '1',
  NUMBER_2 = '2',
  NUMBER_3 = '3',
  NUMBER_4 = '4',
  NUMBER_5 = '5',
  NUMBER_6 = '6',
  NUMBER_7 = '7',
  NUMBER_8 = '8',
  NUMBER_9 = '9',
  NUMBER_0 = '0',

  LOWER_A = 'a',
  LOWER_B = 'b',
  LOWER_C = 'c',
  LOWER_D = 'd',
  LOWER_E = 'e',
  LOWER_F = 'f',
  LOWER_G = 'g',
  LOWER_H = 'h',
  LOWER_I = 'i',
  LOWER_J = 'j',
  LOWER_K = 'k',
  LOWER_L = 'l',
  LOWER_N = 'n',
  LOWER_M = 'm',
  LOWER_O = 'o',
  LOWER_P = 'p',
  LOWER_Q = 'q',
  LOWER_R = 'r',
  LOWER_S = 's',
  LOWER_T = 't',
  LOWER_U = 'u',
  LOWER_V = 'v',
  LOWER_W = 'w',
  LOWER_X = 'x',
  LOWER_Y = 'y',
  LOWER_Z = 'z',

  UPPER_A = 'A',
  UPPER_B = 'B',
  UPPER_C = 'C',
  UPPER_D = 'D',
  UPPER_E = 'E',
  UPPER_F = 'F',
  UPPER_G = 'G',
  UPPER_H = 'H',
  UPPER_I = 'I',
  UPPER_J = 'J',
  UPPER_K = 'K',
  UPPER_L = 'L',
  UPPER_N = 'N',
  UPPER_M = 'M',
  UPPER_O = 'O',
  UPPER_P = 'P',
  UPPER_Q = 'Q',
  UPPER_R = 'R',
  UPPER_S = 'S',
  UPPER_T = 'T',
  UPPER_U = 'U',
  UPPER_V = 'V',
  UPPER_W = 'W',
  UPPER_X = 'X',
  UPPER_Y = 'Y',
  UPPER_Z = 'Z',
}
